### ISSUE TITLE
BUG No output devices in Audio Switcher plugin

### ISSUE THREAD

**Issue by LogicalUnit** [StreamController/AudioSwitcher#4] opened 2024-05-28 11:24 UTC
**Describe the bug**
I am configuring buttons to use with the Audio Switcher/Set device and Audio Switcher/Toggle output actions. Both of these actions have a dropdown option that presumably lists audio devices, but nothing happens when I click it.

**To Reproduce**
1. Choose a button in the page, and add the Audio Switcher - Set device action.
2. Click that action to configure it
3. Click the dropdown menu that says Device
4. Nothing happens
5. Similar issue with the Audio Switch - Toggle Output action

**Expected behavior**
See a list of audio output devices and choose one

**Screenshots**
![Screenshot from 2024-05-28 21-10-48](https://github.com/StreamController/StreamController/assets/6601496/c7128909-7953-48d2-a9d2-1ecbbc20a173)

**Additional context**
Ubuntu 22.04 LTS

**Comment by Core447** [comment] 2024-05-28 19:39
(Unfortunately), I can't reproduce this issue on my computer (Arch). Can you please close the app completely (via the option in the hamburger menu), open it from the command line (`flatpak run com.core447.StreamController`), go into the config area of the set output action and share the output in the console?

**Comment by LogicalUnit** [comment] 2024-05-28 22:29
Here's the output from starting the app and configuring a Set Output button. No specific message seemed to appear when I clicked on the Device dropdown.

![Screenshot from 2024-05-29 08-27-14](https://github.com/StreamController/AudioSwitcher/assets/6601496/750c8dda-fdcf-4968-b945-ca2b29b6aac5)

**Comment by gsterling** [comment] 2024-05-29 16:15
I have the same problem in Ubuntu 24.04.

In `ToggleOutput.py:70` `sink.proplist` doesn't have a `node.name` key. It does in my Arch Linux though. You can use `sink.name` instead.

So instead of:
```
    def get_device_name(self, sink) -> str:
        proplist = sink.proplist
        return proplist.get("node.name")
```
this works:
```
    def get_device_name(self, sink) -> str:
        return sink.name
```

Which returns the same thing as far as I can tell? I have to admit, I haven't looked into, why Arch Linux has this key and Ubuntu doesn't. Either it needs a case switch or you should use `sink.name` which works on both platforms.

**Comment by Core447** [comment] 2024-05-29 20:05
@gsterling Ok, thanks for the debugging. I can add some fallbacks to the plugin to avoid this in the future. The problem is that the pulse properties are not standardized.

**Comment by Core447** [comment] 2024-06-02 12:07
Should be fixed with db6060c91c8a375dd5058a32aba5f9494577ec88. Edit: Can you please test if it works now for you?

**Comment by LogicalUnit** [comment] 2024-06-03 03:43
I tried to build from source but received the following output
![Screenshot from 2024-06-03 13-42-49](https://github.com/StreamController/AudioSwitcher/assets/6601496/82befcb1-42e1-42b1-9a09-a67bda828fb8)

**Comment by Core447** [comment] 2024-06-03 10:57
You may have to install `libgirepository1.0-dev` through apt and rerun the pip install command. However, the changes made to the plugin should already be in the store and therefore available in the Flatpak version as well.

**Comment by LogicalUnit** [comment] 2024-06-14 02:32
@Core447 Still no audio devices available in the dropdown. Anything I can do to assist with debugging?

EDIT: I installed the package mentioned in your previous post but see the following error when trying to run main.py

![Screenshot from 2024-06-14 12-38-44](https://github.com/StreamController/AudioSwitcher/assets/6601496/074f67cb-f281-490b-9daa-af119058bff9)

**Comment by Core447** [comment] 2024-06-14 12:51
> @Core447 Still no audio devices available in the dropdown. Anything I can do to assist with debugging?

I tested it on Ubuntu 24.04 and it works completely fine. Have you checked if the plugin is up to date (in the store) (if not please restart the app after the update just to make sure)? 


> EDIT: I installed the package mentioned in your previous post but see the following error when trying to run main.py

Ubuntu 22.04 ships a pretty old version of libadwaita that is missing some required widgets, so if you want to run it from the source (what you don't need for the plugin update), you will have to update to 24.04

**Comment by LogicalUnit** [comment] 2024-06-16 23:59
I re-added the Audio Switcher plugin from the Store and restarted StreamController. Unfortunately still no device options in the dropdown :(

**Comment by Core447** [comment] 2024-06-17 13:26
I tested it on 22.04 and got the same result. The new version (available through the store) should finally fix this.

**Comment by LogicalUnit** [comment] 2024-06-18 01:00
Woo, it's definitely working now!
![Screenshot from 2024-06-18 10-59-44](https://github.com/StreamController/AudioSwitcher/assets/6601496/a4fbd73c-07b6-49d0-9797-b4a9cb6c4544)

**Comment by Core447** [comment] 2024-06-18 12:04
Nice!

**Closed as completed by Core447** 2024-06-18 12:04 UTC
Labels: bug
